# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module DateTimeOptionalTest
  #  date_time_optional_test client class.
  class DateTimeOptionalTestClient
    # Singleton access to body_params controller.
    # @return [BodyParamsController] Returns the controller instance.
    def body_params
      BodyParamsController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end
  end
end
